project:
  type: website
  output-dir: docs

preview: 
  port: 7777
  browser: true
  watch-inputs: true
  navigate: true

resources:
  - "assets/**"

website:
  title: "Shores of Infinity"
  site-url: https://www.shoresofinfinity.net
  navbar:
    logo: images/golden_dragon_fractal.png
    left:
      - href: index.qmd
        text: Home
      - boardgames/index.qmd
      - blog.qmd
      - publications/index.qmd
    right:
      - icon: rss
        href: blog.xml

format:
  html:
    theme:
      light:
        - journal
        - assets/light-theme.scss
    css: styles.css
    toc: true
    lightbox: true
